### ISSUE TITLE
online merging

### ISSUE THREAD

**Issue by alessandralorenzo** [cbourjau/nittygriddy#14]
Dear experts,
Using nittygriddy on macOS High Sierra, some errors occur at merge online level. 
The output is available at [nitty_merge_online.txt](https://github.com/cbourjau/nittygriddy/files/1444139/nitty_merge_online.txt). 
Thanks in advance

**Comment by cbourjau** [comment]
Thanks for reporting this! I am pretty sure that this is a ROOT6 + AliRoot issue, but I don't have ROOT6 to installed (yet). Root6 requires all interpreted "c" code to have a valid syntax. I think the current issue originates from AliRoot's `AliAnalysisAlien.cxx:2781`. That line calls the interpreter with some very much invalid syntax. So there is not much I can do on the nittygriddy side about this, and this should be fixed upstream. I will open an issue for AliRoot about this in a bit.

Are you able to start an online merging process without nitty, though? I.e. did it work in the tutorial on the previous day?

Cheers,
Christian

**Comment by cbourjau** [comment]
Seems like this was already fixed in the latest version of AliRoot: https://github.com/alisw/AliRoot/commit/e885fad9831c4a87c9461afe5ba9ced8203ba3f9

Its not in the latest tagged release yet but I would expect this fix to be tagged and shipped soon. I hope that will fix it! If you could try it out after you updated to the latest AliRoot and report back it would be a great help.

Cheers,
Christian

**Comment by cbourjau** [comment]
I now have root 6 installed and all seems to work for me. Please report back if you are still having issues
